dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
networks:
  rinkeby:
    eth_usd_price_feed: '0x223'
    verify: True
  ganache-local:
    verify: False
  development:
    verify: False

dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.3.0

compiler:
  solc:
    version: 0.6.6
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.3.0'